obj-$(CONFIG_TOUCHSCREEN_GOODIX_BRL) := goodix_brl_mmi.o
goodix_brl_mmi-objs := \
					goodix_brl_i2c.o \
					goodix_brl_spi.o \
					goodix_ts_core.o \
					goodix_brl_hw.o \
					goodix_cfg_bin.o \
					goodix_ts_utils.o \
					goodix_brl_fwupdate.o \
					goodix_ts_inspect.o \
					goodix_ts_tools.o \
					goodix_ts_config.o

ccflags-$(CONFIG_DRM_PANEL_EVENT_NOTIFICATIONS) += -DCONFIG_DRM_PANEL_EVENT_NOTIFICATIONS
ccflags-$(CONFIG_DRM_PANEL_NOTIFICATIONS) += -DCONFIG_DRM_PANEL_NOTIFICATIONS
ccflags-$(CONFIG_TOUCHSCREEN_GOODIX_BRL_SPI) += -DCONFIG_TOUCHSCREEN_GOODIX_BRL_SPI
ccflags-$(CONFIG_GTP_LIMIT_USE_SUPPLIER) += -DCONFIG_GTP_LIMIT_USE_SUPPLIER
ccflags-$(CONFIG_GTP_ENABLE_PM_QOS) += -DCONFIG_GTP_ENABLE_PM_QOS
ccflags-$(CONFIG_GOODIX_ESD_ENABLE) += -DCONFIG_GOODIX_ESD_ENABLE
ccflags-$(CONFIG_TARGET_BUILD_FACROTY) += -DGTP_SAVE_IN_CSV
ccflags-$(CONFIG_GTP_LAST_TIME) += -DCONFIG_GTP_LAST_TIME
ccflags-$(CONFIG_BOARD_USES_DOUBLE_TAP_CTRL) += -DCONFIG_BOARD_USES_DOUBLE_TAP_CTRL
ccflags-$(CONFIG_INPUT_GOODIX_MMI_ENABLE_PALM) += -DGOODIX_PALM_SENSOR_EN
ccflags-$(CONFIG_MOTO_DDA_PASSIVE_STYLUS) += -DCONFIG_MOTO_DDA_PASSIVESTYLUS
ccflags-$(CONFIG_ENABLE_GTP_PALM_CANCEL) += -DCONFIG_ENABLE_GTP_PALM_CANCEL
ccflags-$(CONFIG_INPUT_GTP_PASSIVE_PEN_NOTIFIER) += -DGTP_PEN_NOTIFIER

ifneq ($(filter m y,$(CONFIG_GTP_FOD)),)
    ccflags-y += -DCONFIG_GTP_FOD
    goodix_brl_mmi-objs += goodix_ts_gesture_fod.o
else
    goodix_brl_mmi-objs += goodix_ts_gesture.o
endif

ifneq ($(filter m y,$(CONFIG_GTP_DDA_STYLUS)),)
    ccflags-y += -DCONFIG_GTP_DDA_STYLUS
    goodix_brl_mmi-objs += goodix_ts_dda.o
endif

ifneq ($(filter m y,$(CONFIG_INPUT_TOUCHSCREEN_MMI)),)
    ccflags-y += -DCONFIG_INPUT_TOUCHSCREEN_MMI
    goodix_brl_mmi-objs += goodix_ts_mmi.o
endif